package com.prueba.gestionriesgos.domain.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;

import javax.validation.constraints.Min;
import javax.validation.constraints.Size;
import java.util.List;

/**
 * Represents a Person.
 * This class is mapped to the "Person" table in the database.
 */
@Data
@NoArgsConstructor
@Entity
@Table(name = "person")
public class Person {

    /**
     * The unique identifier for the curb.
     * It is auto-generated by the database and serves as the primary key of the "person" table.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "person_id")
    private Integer personId;

    /**
     * The name of the person.
     */
    @NonNull
    @Size(min = 1, max = 150, message = "First name must be between 1 and 150 characters")
    @Column(name = "last_name")
    private String firstName;

    /**
     * The age of the person.
     */
    @NonNull
    @Min(value = 0, message = "Age must be a greater than or equal to 0")
    @Column(name = "age")
    private Integer age;

    /**
     * The occupation of the person.
     */
    @NonNull
    @Size(min = 1, max = 150, message = "Occupation must be between 1 and 150 characters")
    @Column(name = "occupation")
    private String occupation;

    /**
     * A list of places associated with the person.
     */
    @OneToMany(mappedBy = "person", cascade = CascadeType.ALL)
    private List<Place> places;
}
